export const APPS_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbxqI-TcTuNHG_ZbPGheuIGg6qCnW8EQiGiT_XABoKWveDfgryhpPdECnCuHZNNq90ZS/exec';

export const LOGO_IMAGE = '/assets/images/download.png';

export const EXAM_PAPERS = {
  'Mainstream': [
    'General Paper',
    'Use of English',
    'Financial Regulations',
    'Computer Appreciation & Literacy',
    'Public Service Rules',
    'Public Service Commission Regulations',
    'Common Law',
  ],
  'Local Government': [
    'General Paper',
    'Use of English',
    'Financial Memoranda',
    'Computer Appreciation & Literacy',
    'Local Government Service Rules',
    'Public Service Commission Regulations',
    'Common Law',
  ],
};

export const OYO_LGAS = [
  'Afijio', 'Akinyele', 'Atiba', 'Atisbo', 'Egbeda',
  'Ibadan North', 'Ibadan North-East', 'Ibadan North-West',
  'Ibadan South-East', 'Ibadan South-West', 'Ibarapa Central',
  'Ibarapa East', 'Ibarapa North', 'Ido', 'Irepo', 'Iseyin',
  'Itesiwaju', 'Iwajowa', 'Kajola', 'Lagelu', 'Ogbomosho North',
  'Ogbomosho South', 'Ogo Oluwa', 'Olorunsogo', 'Oluyole',
  'Ona Ara', 'Orelope', 'Ori Ire', 'Oyo East', 'Oyo West',
  'Saki East', 'Saki West', 'Surulere',
];

export const LGA_ZONE = {
  'Ibadan North':      'IBD',
  'Ibadan North-East': 'IBD',
  'Ibadan North-West': 'IBD',
  'Ibadan South-East': 'IBD',
  'Ibadan South-West': 'IBD',
  'Oluyole':           'IBD',
  'Akinyele':          'IBD',
  'Ido':               'IBD',
  'Egbeda':            'IBD2',
  'Lagelu':            'IBD2',
  'Ona Ara':           'IBD2',
  'Ibarapa Central':   'ERW',
  'Ibarapa East':      'ERW',
  'Ibarapa North':     'ERW',
  'Iseyin':            'ISY',
  'Itesiwaju':         'ISY',
  'Iwajowa':           'ISY',
  'Kajola':            'ISY',
  'Atisbo':            'ISY',
  'Saki East':         'SHK',
  'Saki West':         'SHK',
  'Orelope':           'SHK',
  'Olorunsogo':        'SHK',
  'Irepo':             'SHK',
  'Oyo East':          'OYO',
  'Oyo West':          'OYO',
  'Atiba':             'OYO',
  'Afijio':            'OYO',
  'Ogo Oluwa':         'OYO',
  'Ogbomosho North':   'OGB',
  'Ogbomosho South':   'OGB',
  'Surulere':          'OGB',
  'Ori Ire':           'OGB',
};

export const ZONE_CENTRES = {
  'IBD': [
    'Government College',
    "Queen's School",
    'Apata Community Grammar School',
    'African Church Grammar School',
    'Apata Grammar School',
    'Our Lady of Apostle Secondary Grammar School',
    'St Michael Owode',
  ],
  'IBD2': [
    'Bishop Phillips Academy',
    'Urban Day Secondary School',
    'IDC Primary School',
  ],
  'ERW': [
    'Obaseku High School',
    'Obaseku Grammar School',
  ],
  'ISY': [
    'Iseyin Districts Grammar School',
    'Raji Oke-Esa Memorial High School',
  ],
  'SHK': [
    'Baptist High School',
    'Ansar-U-Deen High School',
    'N.U.D High School',
    'Okere Secondary Grammar School',
    'Oba Kilani Ilufemiloye Secondary School',
  ],
  'OYO': [
    'St Bernadine College',
    'Ilora Baptist High School',
    'Olivet Baptist High School',
  ],
  'OGB': [
    'Owode Community Secondary School',
    'Ogbomoso Grammar School',
    'School of Science',
    'Millenium Model Secondary School',
  ],
};

export const OYO_MDAS = {
  'Office of the Governor': [
    "Governor's Office",
    "Deputy Governor's Office",
    "Chief of Staff's Office",
    'Office of Special Adviser on Strategy',
    'Office of Special Adviser on Media & Publicity',
    'Oyo State Security Trust Fund',
  ],
  'Office of the Secretary to the State Government': [
    'Cabinet Affairs',
    'Establishment & Training',
    'Political & Economic Affairs',
    'Inter-Governmental Relations',
    'Ceremonials & Protocol',
  ],
  'Office of the Head of Service': [
    'Human Resource Management',
    'Career Management Services',
    'Service Policy & Strategy',
    'Public Service Reform',
    'Productivity Measurement',
  ],
  'Ministry of Finance': [
    'Budget & Economic Planning',
    'Treasury & Accounts',
    'Revenue & Taxation',
    'Debt Management',
    'Financial Intelligence Unit',
    'Oyo State Internal Revenue Service (OYIRS)',
    'Oyo State Investment & PPP Agency (OYSIPA)',
  ],
  'Ministry of Education, Science & Technology': [
    'Basic Education',
    'Post-Primary Education',
    'Tertiary Education',
    'Science & Technology',
    'Oyo State Teaching Service Commission (TESCOM)',
    'Oyo State Universal Basic Education Board (OYSUBEB)',
    'Agency for Adult & Non-Formal Education (AANFE)',
    'Oyo State Examinations Board',
    'Oyo State Scholarship Board',
  ],
  'Ministry of Health': [
    'Primary Health Care',
    'Secondary Health Care',
    'Hospital Services',
    'Public Health & Disease Control',
    'Pharmacy & Narcotics',
    'Oyo State Hospitals Management Board (HMB)',
    'Oyo State Agency for the Control of AIDS (OYSACA)',
    'Oyo State Primary Health Care Board',
    'Oyo State Blood Transfusion Service',
  ],
  'Ministry of Agriculture & Natural Resources': [
    'Crop Production',
    'Animal Production & Veterinary Services',
    'Fisheries',
    'Forestry & Natural Resources',
    'Agricultural Extension Services',
    'Oyo State Agricultural Development Programme (OYADEP)',
    'Oyo State Agricultural Land Use & Land Bank Agency',
  ],
  'Ministry of Works & Transport': [
    'Highways & Roads',
    'Bridges & Drainages',
    'Buildings & Housing',
    'Transport Services',
    'Oyo State Road Maintenance Agency (OYROMA)',
    'Oyo State Public Works Corporation (OSPWC)',
    'Oyo State Traffic Management Authority (OYTMA)',
  ],
  'Ministry of Justice': [
    'Civil Litigation',
    'Criminal Prosecution',
    'Public Prosecution',
    'Legislative Drafting',
    'Law Reform Commission',
    "Citizens' Mediation Centre",
    'Oyo State Legal Aid Council',
  ],
  'Ministry of Land, Housing & Urban Development': [
    'Land Administration',
    'Survey & Mapping',
    'Urban & Regional Planning',
    'Housing Development',
    'Oyo State Land Use & Allocation Committee',
    'Oyo State Urban Development Board (OUDB)',
    'Oyo State Property Development Corporation (OSPDC)',
  ],
  'Ministry of Environment': [
    'Environmental Planning & Policy',
    'Pollution Control',
    'Environmental Sanitation',
    'Climate Change & Meteorology',
    'Oyo State Waste Management Authority (OWMA)',
    'Oyo State Environmental Protection Agency (OYSEPA)',
  ],
  'Ministry of Youth & Sports': [
    'Youth Development',
    'Sports Development',
    'NYSC Liaison Office',
    'Oyo State Sports Council',
    'Oyo State Youth Investment Fund',
  ],
  'Ministry of Women Affairs & Social Inclusion': [
    'Women Development',
    'Social Welfare Services',
    'Child Development',
    'People with Disabilities',
    'Oyo State Agency for the Welfare of Indigent Persons',
  ],
  'Ministry of Information, Culture & Tourism': [
    'Information Services',
    'Culture & Arts',
    'Tourism & Hospitality',
    'Broadcasting Services',
    'Oyo State Broadcasting Corporation (BCOS)',
    'Heritage Arts & Culture Bureau',
    'Oyo State Tourism Board',
  ],
  'Ministry of Commerce, Industry & Cooperatives': [
    'Commerce & Trade',
    'Industry & Investment',
    'Cooperatives Services',
    'Consumer Protection',
    'Oyo State Investment Promotion Agency',
    'Oyo State Bureau of Statistics',
  ],
  'Ministry of Energy & Mineral Resources': [
    'Power & Electricity',
    'Petroleum Resources',
    'Mineral Resources',
    'Rural Electrification',
    'Oyo State Rural Electrification Board (OSREB)',
  ],
  'Ministry of Local Government & Community Development': [
    'Local Government Administration',
    'Community Development Services',
    'Traditional Council Affairs',
    'Oyo State Local Government Service Commission',
    'Joint Account Allocation Committee (JAAC)',
  ],
  'Ministry of Public Service & Special Duties': [
    'Public Service Administration',
    'Special Duties & Projects',
    'Service Delivery Monitoring',
    'Oyo State Civil Service Commission',
  ],
  'Ministry of Budget & Economic Planning': [
    'Budget Preparation & Monitoring',
    'Economic Planning',
    'Development Planning',
    'Statistics & Data Management',
    'Oyo State Planning Commission',
  ],
  'Oyo State House of Assembly': [
    "Clerk's Office",
    'Research & Information',
    'Committee Affairs',
    'Administrative Services',
    'Legislative Aides Office',
  ],
  'Oyo State Judiciary': [
    'High Court',
    'Magistrate Courts',
    'Customary Court of Appeal',
    'Sharia Court of Appeal',
    'Judiciary Administrative Services',
    'National Industrial Court (Ibadan Division)',
  ],
  'Oyo State Independent Electoral Commission (OYSIEC)': [
    'Electoral Operations',
    'Voter Registration',
    'Civic Education',
    'Administrative Services',
  ],
  "Oyo State Auditor-General's Office": [
    'State Audit',
    'Local Government Audit',
    'Pre-Payment Audit',
    'Special Audit & Investigation',
  ],
  "Oyo State Accountant-General's Office": [
    'Treasury Operations',
    'Salary & Payroll',
    'Government Revenue',
    'Financial Reporting',
    'Pensions & Gratuities Administration',
  ],
  'Civil Service Commission': [
    'Appointments & Promotions',
    'Discipline',
    'Records & Personnel',
    'Administrative Services',
  ],
  'Local Government Service Commission': [
    'Appointments & Promotions (LG)',
    'Discipline (LG)',
    'Records & Personnel (LG)',
    'Administrative Services (LG)',
  ],
  'Teaching Service Commission (TESCOM)': [
    'Appointments & Promotions (LG)',
    'Discipline (MS)',
    'Records & Personnel',
    'Administrative Services (MS)',
  ],
  'Other Agency / Parastatal': [
    'Specify in remarks — contact the examination office',
  ],
};

export const GRADE_LEVELS = [
  'GL 01', 'GL 02', 'GL 03', 'GL 04', 'GL 05', 'GL 06', 'GL 07',
  'GL 08', 'GL 09', 'GL 10', 'GL 12', 'GL 13', 'GL 14',
  'GL 15', 'GL 16', 'GL 17',
];

export function getCentresForLGA(lga) {
  const zone = LGA_ZONE[lga];
  return zone ? (ZONE_CENTRES[zone] || []) : [];
}
